Connected to base (Python 3.12.4)

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np

In [ ]:
pd.read_csv("CPP_DR.csv")

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
1,2025-3711,3711.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3711
2,2025-7330,7330.0,2025.0,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025.0,I71S1C913J1V1,...,65.0,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65.0,True,Facultad Tecnológica,67.0,Departamento de Tecnologias de Gestión,True,2025-7330
3,2025-4601,4601.0,2025.0,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4601
4,2025-4602,4602.0,2025.0,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,2024-9107,9107.0,2024.0,2024-I71S1C66J2V1,MAGÍSTER EN TELECOMUNICACIONES,NaN,NaN,NaN,NaN,I71S1C66J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,41.0,Departamento de Ingeniería Eléctrica,NaN,2024-9107
7786,2024-9137,9137.0,2024.0,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,NaN,NaN,NaN,NaN,I71S1C56J1V2,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,47.0,Departamento de Ingeniería Química y Bioprocesos,NaN,2024-9137
7787,2021-9484,9484.0,2021.0,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,NaN,NaN,NaN,NaN,I71S1C221J2V1,...,NaN,NaN,NaN,55.0,False,Facultad de Humanidades,59.0,Departamento de Educación,NaN,2021-9484
7788,2022-9193,9193.0,2022.0,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",NaN,NaN,NaN,NaN,I71S1C398J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,40.0,Facultad de Ingeniería,NaN,2022-9193
7789,2025-9728,9728.0,2025.0,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,NaN,NaN,NaN,NaN,I71S1C280J3V1,...,NaN,NaN,NaN,94.0,False,Facultad de Arquitectura y Ambiente Construido,94.0,Facultad de Arquitectura y Ambiente Construido,NaN,2025-9728

In [ ]:
tabla_cpp = pd.read_csv("CPP_DR.csv")
tabla_cpp

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
1,2025-3711,3711.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3711
2,2025-7330,7330.0,2025.0,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025.0,I71S1C913J1V1,...,65.0,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65.0,True,Facultad Tecnológica,67.0,Departamento de Tecnologias de Gestión,True,2025-7330
3,2025-4601,4601.0,2025.0,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4601
4,2025-4602,4602.0,2025.0,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,2024-9107,9107.0,2024.0,2024-I71S1C66J2V1,MAGÍSTER EN TELECOMUNICACIONES,NaN,NaN,NaN,NaN,I71S1C66J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,41.0,Departamento de Ingeniería Eléctrica,NaN,2024-9107
7786,2024-9137,9137.0,2024.0,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,NaN,NaN,NaN,NaN,I71S1C56J1V2,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,47.0,Departamento de Ingeniería Química y Bioprocesos,NaN,2024-9137
7787,2021-9484,9484.0,2021.0,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,NaN,NaN,NaN,NaN,I71S1C221J2V1,...,NaN,NaN,NaN,55.0,False,Facultad de Humanidades,59.0,Departamento de Educación,NaN,2021-9484
7788,2022-9193,9193.0,2022.0,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",NaN,NaN,NaN,NaN,I71S1C398J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,40.0,Facultad de Ingeniería,NaN,2022-9193
7789,2025-9728,9728.0,2025.0,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,NaN,NaN,NaN,NaN,I71S1C280J3V1,...,NaN,NaN,NaN,94.0,False,Facultad de Arquitectura y Ambiente Construido,94.0,Facultad de Arquitectura y Ambiente Construido,NaN,2025-9728

In [ ]:
tabla_cpp.columns

Index(['ID', 'COD_PLAN', 'ANHO', 'ANHO_SIES', 'PLAN_NOMBRE', 'JORNADA_USACH',
       'JORNADA_SIES', 'ESTADO_JORNADA', 'LLAVE', 'SIES', 'LLAVE_SIES',
       'PROGRAMA_SIES', 'OBSERVACIÓN', 'COD_PLAN2', 'COD_CARRERA',
       'Nombre_carrera', 'REPLICA_COD_SIES', 'DURACIÓN', 'DURACION_TOTAL',
       'COD_DEPTO_2', 'COD_FAC_', 'depto', 'FACULTAD_', 'COD_FAC',
       'comparacion_facultad', 'FACULTAD', 'COD_DEPTO_2_CR', 'nombre_depto_cr',
       'comparacion_cod_depto', 'ANHO_PLAN'],
      dtype='object')

In [ ]:
tabla_cpp['ID','COD_PLAN', 'ANHO_PLAN', 'ANHO_SIES']

KeyError: ('ID', 'COD_PLAN', 'ANHO_PLAN', 'ANHO_SIES')

In [ ]:
tabla_cpp[['ID','COD_PLAN', 'ANHO_PLAN', 'ANHO_SIES']]

             ID  COD_PLAN  ANHO_PLAN           ANHO_SIES
0     2025-3701    3701.0  2025-3701    2025-I71S1C2J1V1
1     2025-3711    3711.0  2025-3711    2025-I71S1C2J1V1
2     2025-7330    7330.0  2025-7330  2025-I71S1C913J1V1
3     2025-4601    4601.0  2025-4601   2025-I71S1C39J1V1
4     2025-4602    4602.0  2025-4602   2025-I71S1C39J1V1
...         ...       ...        ...                 ...
7785  2024-9107    9107.0  2024-9107   2024-I71S1C66J2V1
7786  2024-9137    9137.0  2024-9137   2024-I71S1C56J1V2
7787  2021-9484    9484.0  2021-9484  2021-I71S1C221J2V1
7788  2022-9193    9193.0  2022-9193  2022-I71S1C398J2V1
7789  2025-9728    9728.0  2025-9728  2025-I71S1C280J3V1

[7790 rows x 4 columns]

In [ ]:
tabla_cpp[['ID','COD_PLAN', 'ANHO_PLAN', 'ANHO_SIES','PLAN_NOMBRE','COD_CARRERA','CARRERA_NOMBRE','ANHO']]

KeyError: "['CARRERA_NOMBRE'] not in index"

In [ ]:
tabla_cpp[['ID','COD_PLAN', 'ANHO_PLAN', 'ANHO_SIES','PLAN_NOMBRE','COD_CARRERA','COD_FAC','FACULTAD']]

,ID,COD_PLAN,ANHO_PLAN,ANHO_SIES,PLAN_NOMBRE,COD_CARRERA,COD_FAC,FACULTAD
0,2025-3701,3701.0,2025-3701,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,ADMPUB,60.0,Facultad de Administración y Economía
1,2025-3711,3711.0,2025-3711,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),ADMPUB,60.0,Facultad de Administración y Economía
2,2025-7330,7330.0,2025-7330,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,AGPP,65.0,Facultad Tecnológica
3,2025-4601,4601.0,2025-4601,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,LCC,50.0,Facultad de Ciencia
4,2025-4602,4602.0,2025-4602,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,LCC,50.0,Facultad de Ciencia
...,...,...,...,...,...,...,...,...
7785,2024-9107,9107.0,2024-9107,2024-I71S1C66J2V1,MAGÍSTER EN TELECOMUNICACIONES,MAGTCO,40.0,Facultad de Ingeniería
7786,2024-9137,9137.0,2024-9137,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,MAGCDI,40.0,Facultad de Ingeniería
7787,2021-9484,9484.0,2021-9484,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,MAGEDU,55.0,Facultad de Humanidades
7788,2022-9193,9193.0,2022-9193,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",MAGSPA,40.0,Facultad de Ingeniería
7789,2025-9728,9728.0,2025-9728,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,MIDA,94.0,Facultad de Arquitectura y Ambiente Construido

In [ ]:
tabla_cpp[['ID', 'ANHO_SIES','COD_PLAN', 'ANHO_PLAN', 'PLAN_NOMBRE','COD_CARRERA','COD_FAC','FACULTAD']]

,ID,ANHO_SIES,COD_PLAN,ANHO_PLAN,PLAN_NOMBRE,COD_CARRERA,COD_FAC,FACULTAD
0,2025-3701,2025-I71S1C2J1V1,3701.0,2025-3701,ADMINISTRACIÓN PÚBLICA,ADMPUB,60.0,Facultad de Administración y Economía
1,2025-3711,2025-I71S1C2J1V1,3711.0,2025-3711,ADMINISTRACIÓN PÚBLICA (D),ADMPUB,60.0,Facultad de Administración y Economía
2,2025-7330,2025-I71S1C913J1V1,7330.0,2025-7330,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,AGPP,65.0,Facultad Tecnológica
3,2025-4601,2025-I71S1C39J1V1,4601.0,2025-4601,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,LCC,50.0,Facultad de Ciencia
4,2025-4602,2025-I71S1C39J1V1,4602.0,2025-4602,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,LCC,50.0,Facultad de Ciencia
...,...,...,...,...,...,...,...,...
7785,2024-9107,2024-I71S1C66J2V1,9107.0,2024-9107,MAGÍSTER EN TELECOMUNICACIONES,MAGTCO,40.0,Facultad de Ingeniería
7786,2024-9137,2024-I71S1C56J1V2,9137.0,2024-9137,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,MAGCDI,40.0,Facultad de Ingeniería
7787,2021-9484,2021-I71S1C221J2V1,9484.0,2021-9484,MAGÍSTER EN EDUCACIÓN,MAGEDU,55.0,Facultad de Humanidades
7788,2022-9193,2022-I71S1C398J2V1,9193.0,2022-9193,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",MAGSPA,40.0,Facultad de Ingeniería
7789,2025-9728,2025-I71S1C280J3V1,9728.0,2025-9728,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,MIDA,94.0,Facultad de Arquitectura y Ambiente Construido

In [ ]:
tabla_cpp[['ID', 'ANHO_SIES','COD_PLAN', 'ANHO_PLAN', 'PLAN_NOMBRE','COD_CARRERA','COD_FAC','FACULTAD','COD_DEPTO_2_CR']]

,ID,ANHO_SIES,COD_PLAN,ANHO_PLAN,PLAN_NOMBRE,COD_CARRERA,COD_FAC,FACULTAD,COD_DEPTO_2_CR
0,2025-3701,2025-I71S1C2J1V1,3701.0,2025-3701,ADMINISTRACIÓN PÚBLICA,ADMPUB,60.0,Facultad de Administración y Economía,64.0
1,2025-3711,2025-I71S1C2J1V1,3711.0,2025-3711,ADMINISTRACIÓN PÚBLICA (D),ADMPUB,60.0,Facultad de Administración y Economía,64.0
2,2025-7330,2025-I71S1C913J1V1,7330.0,2025-7330,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,AGPP,65.0,Facultad Tecnológica,67.0
3,2025-4601,2025-I71S1C39J1V1,4601.0,2025-4601,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,LCC,50.0,Facultad de Ciencia,51.0
4,2025-4602,2025-I71S1C39J1V1,4602.0,2025-4602,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,LCC,50.0,Facultad de Ciencia,51.0
...,...,...,...,...,...,...,...,...,...
7785,2024-9107,2024-I71S1C66J2V1,9107.0,2024-9107,MAGÍSTER EN TELECOMUNICACIONES,MAGTCO,40.0,Facultad de Ingeniería,41.0
7786,2024-9137,2024-I71S1C56J1V2,9137.0,2024-9137,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,MAGCDI,40.0,Facultad de Ingeniería,47.0
7787,2021-9484,2021-I71S1C221J2V1,9484.0,2021-9484,MAGÍSTER EN EDUCACIÓN,MAGEDU,55.0,Facultad de Humanidades,59.0
7788,2022-9193,2022-I71S1C398J2V1,9193.0,2022-9193,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",MAGSPA,40.0,Facultad de Ingeniería,40.0
7789,2025-9728,2025-I71S1C280J3V1,9728.0,2025-9728,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,MIDA,94.0,Facultad de Arquitectura y Ambiente Construido,94.0

In [ ]:
tabla_cpp[['ID', 
           'ANHO_SIES',
           'COD_PLAN', 
           'ANHO_PLAN', 
           'PLAN_NOMBRE',
           'COD_CARRERA',
           'COD_FAC',
           'FACULTAD',
           'COD_DEPTO_2_CR', 
           'nombre_depto_cr']]

,ID,ANHO_SIES,COD_PLAN,ANHO_PLAN,PLAN_NOMBRE,COD_CARRERA,COD_FAC,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr
0,2025-3701,2025-I71S1C2J1V1,3701.0,2025-3701,ADMINISTRACIÓN PÚBLICA,ADMPUB,60.0,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas
1,2025-3711,2025-I71S1C2J1V1,3711.0,2025-3711,ADMINISTRACIÓN PÚBLICA (D),ADMPUB,60.0,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas
2,2025-7330,2025-I71S1C913J1V1,7330.0,2025-7330,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,AGPP,65.0,Facultad Tecnológica,67.0,Departamento de Tecnologias de Gestión
3,2025-4601,2025-I71S1C39J1V1,4601.0,2025-4601,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,LCC,50.0,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...
4,2025-4602,2025-I71S1C39J1V1,4602.0,2025-4602,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,LCC,50.0,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...
...,...,...,...,...,...,...,...,...,...,...
7785,2024-9107,2024-I71S1C66J2V1,9107.0,2024-9107,MAGÍSTER EN TELECOMUNICACIONES,MAGTCO,40.0,Facultad de Ingeniería,41.0,Departamento de Ingeniería Eléctrica
7786,2024-9137,2024-I71S1C56J1V2,9137.0,2024-9137,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,MAGCDI,40.0,Facultad de Ingeniería,47.0,Departamento de Ingeniería Química y Bioprocesos
7787,2021-9484,2021-I71S1C221J2V1,9484.0,2021-9484,MAGÍSTER EN EDUCACIÓN,MAGEDU,55.0,Facultad de Humanidades,59.0,Departamento de Educación
7788,2022-9193,2022-I71S1C398J2V1,9193.0,2022-9193,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",MAGSPA,40.0,Facultad de Ingeniería,40.0,Facultad de Ingeniería
7789,2025-9728,2025-I71S1C280J3V1,9728.0,2025-9728,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,MIDA,94.0,Facultad de Arquitectura y Ambiente Construido,94.0,Facultad de Arquitectura y Ambiente Construido

In [ ]:
tabla_cpp_sel

NameError: name 'tabla_cpp_sel' is not defined

In [ ]:
tabla_cpp_sel=st.selectbox("Selecciona el código a visualizar:", 
         tabla_cpp['COD_PLAN'].unique())

2026-04-27 10:52:15.756 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 10:52:15.756 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 10:52:15.758 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 10:52:15.759 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 10:52:15.759 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-04-27 10:52:15.760 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 10:52:15.792
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/xenomorfo/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]
2026-04-27 10:52:15.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 10:52:15.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
tabla_cpp_sel

3701.0

In [ ]:
tabla_filtrada

NameError: name 'tabla_filtrada' is not defined

In [ ]:
tabla_filtrada=tabla_cpp[[tabla_cpp['COD_PLAN']==tabla_cpp_sel]]

KeyError: "None of [Index([(True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, ...)], dtype='object')] are in the [columns]"

In [ ]:
tabla_filtrada=tabla_cpp[[tabla_cpp['COD_PLAN']==tabla_cpp_sel]]

KeyError: "None of [Index([(True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, ...)], dtype='object')] are in the [columns]"

In [ ]:
tabla_filtrada=tabla_cpp[tabla_cpp['COD_PLAN']==tabla_cpp_sel]

In [ ]:
tabla_filtrada

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
377,2024-3701,3701.0,2024.0,2024-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012024.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2024-3701
746,2023-3701,3701.0,2023.0,2023-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012023.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2023-3701
1139,2022-3701,3701.0,2022.0,2022-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012022.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2022-3701
1515,2021-3701,3701.0,2021.0,2021-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012021.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2021-3701
1889,2020-3701,3701.0,2020.0,2020-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012020.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2020-3701
2288,2019-3701,3701.0,2019.0,2019-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012019.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2019-3701
2712,2018-3701,3701.0,2018.0,2018-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012018.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2018-3701
3108,2017-3701,3701.0,2017.0,2017-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012017.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2017-3701
3507,2016-3701,3701.0,2016.0,2016-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012016.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2016-3701
3900,2015-3701,3701.0,2015.0,2015-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012015.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2015-3701
4265,2014-3701,3701.0,2014.0,2014-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012014.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2014-3701
4627,2013-3701,3701.0,2013.0,2013-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012013.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2013-3701
4946,2012-3701,3701.0,2012.0,2012-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012012.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2012-3701
5268,2011-3701,3701.0,2011.0,2011-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012011.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2011-3701
5564,2010-3701,3701.0,2010.0,2010-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012010.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2010-3701
5852,2009-3701,3701.0,2009.0,2009-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012009.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2009-3701
6134,2008-3701,3701.0,2008.0,2008-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012008.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2008-3701
6424,2007-3701,3701.0,2007.0,2007-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012007.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2007-3701
6708,2006-3701,3701.0,2006.0,2006-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012006.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2006-3701
6949,2005-3701,3701.0,2005.0,2005-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012005.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2005-3701
7192,2004-3701,3701.0,2004.0,2004-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012004.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2004-3701

In [ ]:
programas

NameError: name 'programas' is not defined

In [ ]:
programas = tabla_cpp['COD_PLAN'].unique()

In [ ]:
programas

array([3701., 3711., 7330., 4601., 4602., 4609., 5110., 5210., 5310.,
       4260., 5031., 5032., 4110., 4111., 3605., 3607., 3611., 3613.,
       5501., 9820., 9777., 9891., 9895., 9024., 9677., 9058., 9042.,
       9798., 9642., 9255., 9638., 9682., 9645., 9779., 9966., 9254.,
       9796., 9641., 9965., 9218., 9131., 9793., 9128., 9767., 9628.,
       9043., 9130., 3900., 9632., 9625., 9780., 9057., 9844., 9825.,
       9969., 9253., 9227., 9892., 9517., 9678., 9897., 9782., 9781.,
       9928., 9369., 9957., 9775., 9627., 9055., 9617., 9926., 7320.,
       7100., 9215., 9230., 9223., 9214., 9626., 9372., 9476., 9769.,
       9124., 9109., 9110., 9256., 9186., 9776., 9410., 9411., 9479.,
       9213., 9508., 9205., 9514., 8012., 8112., 9815., 9807., 9871.,
       9865., 9812., 9803., 9817., 9823., 9884., 9808., 9813., 9860.,
       9804., 9836., 9894., 9816., 9833., 9814., 9805., 9893., 9806.,
       1341., 1841., 1444., 1441., 1741., 1440., 1361., 1461., 1861.,
       1362., 1462., 1862., 1445., 1363., 1463., 1863., 1963., 1365.,
       1465., 1865., 1366., 1466., 1866., 1067., 1367., 1467., 1867.,
       1018., 1368., 1468., 1868., 1369., 1469., 1669., 1869., 1442.,
       1364., 1464., 1864., 1443., 3506., 3511., 3514., 7311., 7312.,
       1349., 1849., 1353., 1853., 1351., 1451., 1851., 1951., 1352.,
       1852., 1355., 1455., 1356., 1856., 1357., 1857., 1359., 1859.,
       1459., 1354., 1454., 1854., 1954., 7303., 7307., 1340., 1840.,
       4701., 4702., 4800., 4351., 4352., 8020., 8117., 8217., 8218.,
       8116., 8216., 6446., 6447., 6534., 6635., 6429., 6529., 9036.,
       9305., 9301., 9929., 9225., 9224., 9494., 9117., 9115., 9113.,
       9114., 9790., 9116., 9672., 9930., 9051., 9309., 9088., 3916.,
       9307., 9424., 9486., 9204., 9556., 9563., 9562., 9461., 9435.,
       9489., 9488., 9691., 9180., 9306., 9623., 9501., 9414., 9692.,
       9104., 9784., 9797., 9266., 9106., 9487., 9433., 9490., 9022.,
       9121., 9122., 9119., 9260., 9304., 9419., 9492., 9202., 9896.,
       8911., 9181., 9786., 9105., 9750., 9708., 8111., 8119., 8018.,
       8118., 6962., 6331., 6431., 8114., 8014., 8015., 6443., 6543.,
       6428., 6528., 4251., 4252., 6634., 6335., 6435., 6436., 4500.,
       4503., 4513., 4180., 4181., 4182., 5108., 5112., 5101., 5111.,
       7076., 3712., 1021., 1022., 1023., 3604., 3609., 3612., 3614.,
       7841., 1771., 1991., 1873., 1973., 1994., 1975., 1776., 1777.,
       1977., 1268., 1168., 1470., 1974., 3509., 3513., 3512., 3517.,
       3518., 3519., 1998., 1883., 1983., 1993., 1781., 1791., 1978.,
       1882., 1982., 1985., 1889., 1471., 1984., 4150., 9810., 7949.,
       7086., 7947., 9162., 9120., 5107., 6749., 6849., 5121., 5222.,
       5223., 6968., 7040., 4401., 4440., 4441., 6991., 6992., 6873.,
       6874., 7241., 7049., 7069., 7079., 7044., 7048., 7047., 7067.,
       7043., 7063., 7041., 7045., 7042., 8021., 8214., 1890., 2950.,
       2951., 2952., 2953., 2954., 2956., 2957., 2958., 2959., 2960.,
       2961., 2963., 2964., 2966., 2967., 2968., 2969., 2970., 2971.,
       2972., 2973., 2975., 2976., 2977., 2979., 2980., 2981., 2982.,
       2984., 9060., 9800., 9354., 9699., 9380., 9053., 9799., 9392.,
       9252., 9961., 9407., 9519., 9390., 9671., 9355., 9324., 9345.,
       9656., 9946., 9176., 9491., 9513., 9764., 9695., 9399., 9334.,
       9751., 9927., 9212., 9602., 9111., 9811., 9835., 1061., 1961.,
       1953., 9201., 9455., 9484., 9432., 9193., 7305., 8115., 2965.,
       2983., 2987., 2988., 2989., 6978., 7064., 7068., 7061., 7065.,
       7062., 9792., 9322., 9643., 9687., 9876., 9953., 9023., 9875.,
       9344., 9868., 9880., 9393., 9819., 9383., 9851., 9340., 9866.,
       9640., 9663., 9890., 9889., 9376., 9475., 1066., 1966., 1967.,
       1968., 3501., 1053., 1057., 1957., 4359., 9801., 9422., 9416.,
       9436., 9460., 9420., 9421., 9864., 9107., 9705., 7300., 6434.,
       3702., 3508., 1749., 1989., 1986., 9838., 9310., 9315., 9453.,
       9511., 9363., 9877., 5105., 6649., 2955., 2962., 2978., 5120.,
       9831., 6965., 1892., 1941., 6379., 9690., 9000., 9693., 9149.,
       9954., 9217., 9711., 9497., 9955., 9670., 9445., 9919., 9694.,
       9757., 9145., 9684., 9362., 9426., 9773., 9709., 1769., 1056.,
       9312., 3703., 6536., 1898., 4501., 9359., 9758., 9308., 9216.,
       5102., 9828., 6877., 6980., 6963., 6369., 7059., 6976., 9950.,
       9680., 9685., 9636., 9756., 9219., 9785., 9481., 9873., 9952.,
       9183., 9366., 9483., 9350., 9634., 9882., 9870., 1962., 1964.,
       1855., 1955., 4350., 4600., 9387., 9423., 6876., 1981., 7054.,
       9158., 9450., 6349., 6449., 6549., 9869., 6979., 6863., 9341.,
       9382., 9921., 9659., 9512., 9661., 9654., 9629., 1969., 7302.,
       1948., 1956., 1054., 9459., 9365., 9853., 9867., 5106., 9824.,
       6969., 6977., 6966., 7077., 1999., 6985., 9630., 9502., 9752.,
       9945., 9932., 8011., 9451., 9156., 9198., 9652., 9653., 4100.,
       9931., 9454., 9172., 9428., 9651., 9398., 9397., 9754., 9903.,
       9127., 9637., 1064., 1065., 1965., 1949., 1051., 9103., 1773.,
       4797., 6997., 9157., 9482., 9503., 6350., 6964., 9197., 9391.,
       9425., 9427., 9448., 9948., 3603., 9473., 9330., 9469., 9396.,
       9622., 9438., 9924., 9182., 9949., 9822., 9477., 7301., 1848.,
       1850., 9108., 3503., 1980., 7096., 7098., 6334., 9856., 9437.,
       9222., 9942., 9843., 1055., 4700., 9704., 3704., 1774., 6986.,
       6328., 9220., 6865., 7084., 7094., 9842., 9845., 9937., 9938.,
       9923., 9449., 9189., 9439., 9178., 9939., 1068., 6975., 1959.,
       9415., 8016., 3502., 1992., 6878., 6333., 6674., 6982., 9371.,
       9374., 9612., 9934., 9935., 9331., 9329., 9936., 9170., 9507.,
       9618., 1952., 9412., 6535., 7090., 9175., 9126., 5020., 9326.,
       9320., 9323., 9818., 9468., 9606., 1950., 9405., 9403., 9413.,
       1971., 1979., 5001., 6869., 6879., 6981., 1256., 6185., 6385.,
       9605., 9920., 9348., 9352., 9174., 1052., 4300., 9404., 4502.,
       6342., 6983., 7093., 7091., 7095., 6332., 9318., 9343., 9346.,
       9347., 9356., 9504., 9613., 9933., 9999., 3608., 9342., 9357.,
       9358., 9171., 9327., 1063., 1017., 1019., 7304., 4250., 6329.,
       4400., 6376., 5030., 3601., 6343., 6988., 9206., 6880., 6336.,
       6340., 1050., 9402., 3507., 7089., 7099., 6359., 7081., 7085.,
       3602., 1020., 7088., 7087., 7097., 6996., 7267., 7083., 1370.,
       1472., 1473., 1474., 1778., 3515., 8127., 1475., 8121.,    0.,
       1446., 1449., 1269., 3520., 7110., 1480., 1481.,   nan, 9580.,
       9570., 9564., 9571., 9574., 9582., 9520., 9515., 9264., 9273.,
       9261., 3927., 3904., 9299., 9086., 9165., 9298., 9259., 9295.,
       3932., 3923., 3922., 1501., 3913., 9276., 9992., 9168., 9977.,
       9169., 9516., 7914., 9284., 3910., 9073., 5900., 9099., 9281.,
       9560., 3925., 9084., 7905., 9081., 7916., 7909., 3930., 8947.,
       9092., 9565., 7901., 9094., 9091., 9231., 9068., 9067., 9065.,
       9263., 7908., 9049., 3921., 9979., 9087., 8903., 7902., 9085.,
       8909., 9576., 9098., 9095., 7913., 3936., 3929., 9097., 7907.,
       9093., 7903., 8928., 9572., 9569., 8902., 9557., 9279., 3912.,
       9270., 9561., 3917., 7904., 8920., 3934., 9647., 8921., 9976.,
       9981., 8918., 9635., 8934., 7911., 9277., 3924., 3914., 9167.,
       9134., 3926., 9296., 3933., 1500., 9718., 9257., 9089., 9135.,
       9293., 9288., 9137., 9133., 9728.])

In [ ]:
programas = tabla_cpp['COD_PLAN'].unique().dropna()

AttributeError: 'numpy.ndarray' object has no attribute 'dropna'

In [ ]:
programas = tabla_cpp['COD_PLAN'].unique()

In [ ]:
programas

array([3701., 3711., 7330., 4601., 4602., 4609., 5110., 5210., 5310.,
       4260., 5031., 5032., 4110., 4111., 3605., 3607., 3611., 3613.,
       5501., 9820., 9777., 9891., 9895., 9024., 9677., 9058., 9042.,
       9798., 9642., 9255., 9638., 9682., 9645., 9779., 9966., 9254.,
       9796., 9641., 9965., 9218., 9131., 9793., 9128., 9767., 9628.,
       9043., 9130., 3900., 9632., 9625., 9780., 9057., 9844., 9825.,
       9969., 9253., 9227., 9892., 9517., 9678., 9897., 9782., 9781.,
       9928., 9369., 9957., 9775., 9627., 9055., 9617., 9926., 7320.,
       7100., 9215., 9230., 9223., 9214., 9626., 9372., 9476., 9769.,
       9124., 9109., 9110., 9256., 9186., 9776., 9410., 9411., 9479.,
       9213., 9508., 9205., 9514., 8012., 8112., 9815., 9807., 9871.,
       9865., 9812., 9803., 9817., 9823., 9884., 9808., 9813., 9860.,
       9804., 9836., 9894., 9816., 9833., 9814., 9805., 9893., 9806.,
       1341., 1841., 1444., 1441., 1741., 1440., 1361., 1461., 1861.,
       1362., 1462., 1862., 1445., 1363., 1463., 1863., 1963., 1365.,
       1465., 1865., 1366., 1466., 1866., 1067., 1367., 1467., 1867.,
       1018., 1368., 1468., 1868., 1369., 1469., 1669., 1869., 1442.,
       1364., 1464., 1864., 1443., 3506., 3511., 3514., 7311., 7312.,
       1349., 1849., 1353., 1853., 1351., 1451., 1851., 1951., 1352.,
       1852., 1355., 1455., 1356., 1856., 1357., 1857., 1359., 1859.,
       1459., 1354., 1454., 1854., 1954., 7303., 7307., 1340., 1840.,
       4701., 4702., 4800., 4351., 4352., 8020., 8117., 8217., 8218.,
       8116., 8216., 6446., 6447., 6534., 6635., 6429., 6529., 9036.,
       9305., 9301., 9929., 9225., 9224., 9494., 9117., 9115., 9113.,
       9114., 9790., 9116., 9672., 9930., 9051., 9309., 9088., 3916.,
       9307., 9424., 9486., 9204., 9556., 9563., 9562., 9461., 9435.,
       9489., 9488., 9691., 9180., 9306., 9623., 9501., 9414., 9692.,
       9104., 9784., 9797., 9266., 9106., 9487., 9433., 9490., 9022.,
       9121., 9122., 9119., 9260., 9304., 9419., 9492., 9202., 9896.,
       8911., 9181., 9786., 9105., 9750., 9708., 8111., 8119., 8018.,
       8118., 6962., 6331., 6431., 8114., 8014., 8015., 6443., 6543.,
       6428., 6528., 4251., 4252., 6634., 6335., 6435., 6436., 4500.,
       4503., 4513., 4180., 4181., 4182., 5108., 5112., 5101., 5111.,
       7076., 3712., 1021., 1022., 1023., 3604., 3609., 3612., 3614.,
       7841., 1771., 1991., 1873., 1973., 1994., 1975., 1776., 1777.,
       1977., 1268., 1168., 1470., 1974., 3509., 3513., 3512., 3517.,
       3518., 3519., 1998., 1883., 1983., 1993., 1781., 1791., 1978.,
       1882., 1982., 1985., 1889., 1471., 1984., 4150., 9810., 7949.,
       7086., 7947., 9162., 9120., 5107., 6749., 6849., 5121., 5222.,
       5223., 6968., 7040., 4401., 4440., 4441., 6991., 6992., 6873.,
       6874., 7241., 7049., 7069., 7079., 7044., 7048., 7047., 7067.,
       7043., 7063., 7041., 7045., 7042., 8021., 8214., 1890., 2950.,
       2951., 2952., 2953., 2954., 2956., 2957., 2958., 2959., 2960.,
       2961., 2963., 2964., 2966., 2967., 2968., 2969., 2970., 2971.,
       2972., 2973., 2975., 2976., 2977., 2979., 2980., 2981., 2982.,
       2984., 9060., 9800., 9354., 9699., 9380., 9053., 9799., 9392.,
       9252., 9961., 9407., 9519., 9390., 9671., 9355., 9324., 9345.,
       9656., 9946., 9176., 9491., 9513., 9764., 9695., 9399., 9334.,
       9751., 9927., 9212., 9602., 9111., 9811., 9835., 1061., 1961.,
       1953., 9201., 9455., 9484., 9432., 9193., 7305., 8115., 2965.,
       2983., 2987., 2988., 2989., 6978., 7064., 7068., 7061., 7065.,
       7062., 9792., 9322., 9643., 9687., 9876., 9953., 9023., 9875.,
       9344., 9868., 9880., 9393., 9819., 9383., 9851., 9340., 9866.,
       9640., 9663., 9890., 9889., 9376., 9475., 1066., 1966., 1967.,
       1968., 3501., 1053., 1057., 1957., 4359., 9801., 9422., 9416.,
       9436., 9460., 9420., 9421., 9864., 9107., 9705., 7300., 6434.,
       3702., 3508., 1749., 1989., 1986., 9838., 9310., 9315., 9453.,
       9511., 9363., 9877., 5105., 6649., 2955., 2962., 2978., 5120.,
       9831., 6965., 1892., 1941., 6379., 9690., 9000., 9693., 9149.,
       9954., 9217., 9711., 9497., 9955., 9670., 9445., 9919., 9694.,
       9757., 9145., 9684., 9362., 9426., 9773., 9709., 1769., 1056.,
       9312., 3703., 6536., 1898., 4501., 9359., 9758., 9308., 9216.,
       5102., 9828., 6877., 6980., 6963., 6369., 7059., 6976., 9950.,
       9680., 9685., 9636., 9756., 9219., 9785., 9481., 9873., 9952.,
       9183., 9366., 9483., 9350., 9634., 9882., 9870., 1962., 1964.,
       1855., 1955., 4350., 4600., 9387., 9423., 6876., 1981., 7054.,
       9158., 9450., 6349., 6449., 6549., 9869., 6979., 6863., 9341.,
       9382., 9921., 9659., 9512., 9661., 9654., 9629., 1969., 7302.,
       1948., 1956., 1054., 9459., 9365., 9853., 9867., 5106., 9824.,
       6969., 6977., 6966., 7077., 1999., 6985., 9630., 9502., 9752.,
       9945., 9932., 8011., 9451., 9156., 9198., 9652., 9653., 4100.,
       9931., 9454., 9172., 9428., 9651., 9398., 9397., 9754., 9903.,
       9127., 9637., 1064., 1065., 1965., 1949., 1051., 9103., 1773.,
       4797., 6997., 9157., 9482., 9503., 6350., 6964., 9197., 9391.,
       9425., 9427., 9448., 9948., 3603., 9473., 9330., 9469., 9396.,
       9622., 9438., 9924., 9182., 9949., 9822., 9477., 7301., 1848.,
       1850., 9108., 3503., 1980., 7096., 7098., 6334., 9856., 9437.,
       9222., 9942., 9843., 1055., 4700., 9704., 3704., 1774., 6986.,
       6328., 9220., 6865., 7084., 7094., 9842., 9845., 9937., 9938.,
       9923., 9449., 9189., 9439., 9178., 9939., 1068., 6975., 1959.,
       9415., 8016., 3502., 1992., 6878., 6333., 6674., 6982., 9371.,
       9374., 9612., 9934., 9935., 9331., 9329., 9936., 9170., 9507.,
       9618., 1952., 9412., 6535., 7090., 9175., 9126., 5020., 9326.,
       9320., 9323., 9818., 9468., 9606., 1950., 9405., 9403., 9413.,
       1971., 1979., 5001., 6869., 6879., 6981., 1256., 6185., 6385.,
       9605., 9920., 9348., 9352., 9174., 1052., 4300., 9404., 4502.,
       6342., 6983., 7093., 7091., 7095., 6332., 9318., 9343., 9346.,
       9347., 9356., 9504., 9613., 9933., 9999., 3608., 9342., 9357.,
       9358., 9171., 9327., 1063., 1017., 1019., 7304., 4250., 6329.,
       4400., 6376., 5030., 3601., 6343., 6988., 9206., 6880., 6336.,
       6340., 1050., 9402., 3507., 7089., 7099., 6359., 7081., 7085.,
       3602., 1020., 7088., 7087., 7097., 6996., 7267., 7083., 1370.,
       1472., 1473., 1474., 1778., 3515., 8127., 1475., 8121.,    0.,
       1446., 1449., 1269., 3520., 7110., 1480., 1481.,   nan, 9580.,
       9570., 9564., 9571., 9574., 9582., 9520., 9515., 9264., 9273.,
       9261., 3927., 3904., 9299., 9086., 9165., 9298., 9259., 9295.,
       3932., 3923., 3922., 1501., 3913., 9276., 9992., 9168., 9977.,
       9169., 9516., 7914., 9284., 3910., 9073., 5900., 9099., 9281.,
       9560., 3925., 9084., 7905., 9081., 7916., 7909., 3930., 8947.,
       9092., 9565., 7901., 9094., 9091., 9231., 9068., 9067., 9065.,
       9263., 7908., 9049., 3921., 9979., 9087., 8903., 7902., 9085.,
       8909., 9576., 9098., 9095., 7913., 3936., 3929., 9097., 7907.,
       9093., 7903., 8928., 9572., 9569., 8902., 9557., 9279., 3912.,
       9270., 9561., 3917., 7904., 8920., 3934., 9647., 8921., 9976.,
       9981., 8918., 9635., 8934., 7911., 9277., 3924., 3914., 9167.,
       9134., 3926., 9296., 3933., 1500., 9718., 9257., 9089., 9135.,
       9293., 9288., 9137., 9133., 9728.])

In [ ]:
programas = tabla_cpp['COD_PLAN'].unique().to_cliboard()

AttributeError: 'numpy.ndarray' object has no attribute 'to_cliboard'

In [ ]:
programas = pd.DataFrame(tabla_cpp['COD_PLAN'].unique())

In [ ]:
programas

          0
0    3701.0
1    3711.0
2    7330.0
3    4601.0
4    4602.0
..      ...
954  9293.0
955  9288.0
956  9137.0
957  9133.0
958  9728.0

[959 rows x 1 columns]

In [ ]:
programas = pd.DataFrame(tabla_cpp['COD_PLAN'].unique()).dropna()

In [ ]:
programas

          0
0    3701.0
1    3711.0
2    7330.0
3    4601.0
4    4602.0
..      ...
954  9293.0
955  9288.0
956  9137.0
957  9133.0
958  9728.0

[958 rows x 1 columns]

In [ ]:
tabla_cpp = pd.read_csv("CPP_DR.csv")

In [ ]:
if len(sel) == 0:
    tabla_cpp
else:
    tabla_filtrada_2

NameError: name 'sel' is not defined

In [ ]:
sel=st.selectbox("Selecciona el código a visualizar:", 
         tabla_cpp['COD_PLAN'].unique())

2026-04-27 11:39:40.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:39:40.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:39:40.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:39:40.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:39:40.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:39:40.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:39:40.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
tabla_filtrada_2=tabla_cpp[tabla_cpp['COD_PLAN']==sel]

In [ ]:
if len(sel) == 0:
    tabla_cpp
else:
    tabla_filtrada_2

TypeError: object of type 'float' has no len()

In [ ]:
sel

3701.0

In [ ]:
len(sel)

TypeError: object of type 'float' has no len()

In [ ]:
len(sel).astype(str)

TypeError: object of type 'float' has no len()

In [ ]:
tabla_cpp['COD_PLAN'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
len(sel)

TypeError: object of type 'float' has no len()

In [ ]:
tabla_cpp['COD_PLAN'] = tabla_cpp['COD_PLAN'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
tabla_cpp['COD_PLAN'] = tabla_cpp['COD_PLAN'].astype(str)

In [ ]:
len(sel)

TypeError: object of type 'float' has no len()

In [ ]:
sel=st.selectbox("Selecciona el código a visualizar:", 
         tabla_cpp['COD_PLAN'].unique())

2026-04-27 11:42:41.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:42:41.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:42:41.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:42:41.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:42:41.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:42:41.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:42:41.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
len(sel)

6

In [ ]:
if len(sel) == 0:
    tabla_cpp
else:
    tabla_filtrada_2

In [ ]:
len(sel)

6

In [ ]:
sel=st.selectbox("Selecciona el código a visualizar:", 
         tabla_cpp['COD_PLAN'].unique())

tabla_filtrada_2=tabla_cpp[tabla_cpp['COD_PLAN']==sel]

2026-04-27 11:43:36.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:43:36.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:43:36.941 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:43:36.941 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:43:36.942 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:43:36.942 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 11:43:36.942 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
if len(sel) == 0:
    tabla_cpp
else:
    tabla_filtrada_2

In [ ]:
tabla_cpp

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
1,2025-3711,3711.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3711
2,2025-7330,7330.0,2025.0,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025.0,I71S1C913J1V1,...,65.0,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65.0,True,Facultad Tecnológica,67.0,Departamento de Tecnologias de Gestión,True,2025-7330
3,2025-4601,4601.0,2025.0,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4601
4,2025-4602,4602.0,2025.0,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,2024-9107,9107.0,2024.0,2024-I71S1C66J2V1,MAGÍSTER EN TELECOMUNICACIONES,NaN,NaN,NaN,NaN,I71S1C66J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,41.0,Departamento de Ingeniería Eléctrica,NaN,2024-9107
7786,2024-9137,9137.0,2024.0,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,NaN,NaN,NaN,NaN,I71S1C56J1V2,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,47.0,Departamento de Ingeniería Química y Bioprocesos,NaN,2024-9137
7787,2021-9484,9484.0,2021.0,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,NaN,NaN,NaN,NaN,I71S1C221J2V1,...,NaN,NaN,NaN,55.0,False,Facultad de Humanidades,59.0,Departamento de Educación,NaN,2021-9484
7788,2022-9193,9193.0,2022.0,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",NaN,NaN,NaN,NaN,I71S1C398J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,40.0,Facultad de Ingeniería,NaN,2022-9193
7789,2025-9728,9728.0,2025.0,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,NaN,NaN,NaN,NaN,I71S1C280J3V1,...,NaN,NaN,NaN,94.0,False,Facultad de Arquitectura y Ambiente Construido,94.0,Facultad de Arquitectura y Ambiente Construido,NaN,2025-9728

In [ ]:
tabla_cpp.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
tabla_cpp.drop_duplicates()

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
1,2025-3711,3711.0,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3711
2,2025-7330,7330.0,2025.0,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025.0,I71S1C913J1V1,...,65.0,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65.0,True,Facultad Tecnológica,67.0,Departamento de Tecnologias de Gestión,True,2025-7330
3,2025-4601,4601.0,2025.0,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4601
4,2025-4602,4602.0,2025.0,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,2024-9107,9107.0,2024.0,2024-I71S1C66J2V1,MAGÍSTER EN TELECOMUNICACIONES,NaN,NaN,NaN,NaN,I71S1C66J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,41.0,Departamento de Ingeniería Eléctrica,NaN,2024-9107
7786,2024-9137,9137.0,2024.0,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,NaN,NaN,NaN,NaN,I71S1C56J1V2,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,47.0,Departamento de Ingeniería Química y Bioprocesos,NaN,2024-9137
7787,2021-9484,9484.0,2021.0,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,NaN,NaN,NaN,NaN,I71S1C221J2V1,...,NaN,NaN,NaN,55.0,False,Facultad de Humanidades,59.0,Departamento de Educación,NaN,2021-9484
7788,2022-9193,9193.0,2022.0,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",NaN,NaN,NaN,NaN,I71S1C398J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,40.0,Facultad de Ingeniería,NaN,2022-9193
7789,2025-9728,9728.0,2025.0,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,NaN,NaN,NaN,NaN,I71S1C280J3V1,...,NaN,NaN,NaN,94.0,False,Facultad de Arquitectura y Ambiente Construido,94.0,Facultad de Arquitectura y Ambiente Construido,NaN,2025-9728

In [ ]:
tabla_cpp = tabla_cpp.drop_duplicates()

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(layout="wide")

tabla_cpp = pd.read_csv("CPP_DR.csv")

tabla_cpp = tabla_cpp.drop_duplicates()

2026-04-27 11:51:33.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(layout="wide")

tabla_cpp = pd.read_csv("CPP_DR.csv")

tabla_cpp = tabla_cpp.drop_duplicates()

2026-04-27 11:51:47.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
tabla_cpp

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
1,2025-3711,3711,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3711
2,2025-7330,7330,2025.0,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025.0,I71S1C913J1V1,...,65.0,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65.0,True,Facultad Tecnológica,67.0,Departamento de Tecnologias de Gestión,True,2025-7330
3,2025-4601,4601,2025.0,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4601
4,2025-4602,4602,2025.0,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025.0,I71S1C39J1V1,...,50.0,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50.0,True,Facultad de Ciencia,51.0,Departamento de Matemática y Ciencia de la Com...,True,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7786,2024-9137,9137,2024.0,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,NaN,NaN,NaN,NaN,I71S1C56J1V2,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,47.0,Departamento de Ingeniería Química y Bioprocesos,NaN,2024-9137
7787,2021-9484,9484,2021.0,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,NaN,NaN,NaN,NaN,I71S1C221J2V1,...,NaN,NaN,NaN,55.0,False,Facultad de Humanidades,59.0,Departamento de Educación,NaN,2021-9484
7788,2022-9193,9193,2022.0,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",NaN,NaN,NaN,NaN,I71S1C398J2V1,...,NaN,NaN,NaN,40.0,False,Facultad de Ingeniería,40.0,Facultad de Ingeniería,NaN,2022-9193
7789,2025-9728,9728,2025.0,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,NaN,NaN,NaN,NaN,I71S1C280J3V1,...,NaN,NaN,NaN,94.0,False,Facultad de Arquitectura y Ambiente Construido,94.0,Facultad de Arquitectura y Ambiente Construido,NaN,2025-9728
7790,NaN,TODOS,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-

In [ ]:
tabla_cpp['COD_PLAN'].unique()

array(['3701', '3711', '7330', '4601', '4602', '4609', '5110', '5210',
       '5310', '4260', '5031', '5032', '4110', '4111', '3605', '3607',
       '3611', '3613', '5501', '9820', '9777', '9891', '9895', '9024',
       '9677', '9058', '9042', '9798', '9642', '9255', '9638', '9682',
       '9645', '9779', '9966', '9254', '9796', '9641', '9965', '9218',
       '9131', '9793', '9128', '9767', '9628', '9043', '9130', '3900',
       '9632', '9625', '9780', '9057', '9844', '9825', '9969', '9253',
       '9227', '9892', '9517', '9678', '9897', '9782', '9781', '9928',
       '9369', '9957', '9775', '9627', '9055', '9617', '9926', '7320',
       '7100', '9215', '9230', '9223', '9214', '9626', '9372', '9476',
       '9769', '9124', '9109', '9110', '9256', '9186', '9776', '9410',
       '9411', '9479', '9213', '9508', '9205', '9514', '8012', '8112',
       '9815', '9807', '9871', '9865', '9812', '9803', '9817', '9823',
       '9884', '9808', '9813', '9860', '9804', '9836', '9894', '9816',
       '9833', '9814', '9805', '9893', '9806', '1341', '1841', '1444',
       '1441', '1741', '1440', '1361', '1461', '1861', '1362', '1462',
       '1862', '1445', '1363', '1463', '1863', '1963', '1365', '1465',
       '1865', '1366', '1466', '1866', '1067', '1367', '1467', '1867',
       '1018', '1368', '1468', '1868', '1369', '1469', '1669', '1869',
       '1442', '1364', '1464', '1864', '1443', '3506', '3511', '3514',
       '7311', '7312', '1349', '1849', '1353', '1853', '1351', '1451',
       '1851', '1951', '1352', '1852', '1355', '1455', '1356', '1856',
       '1357', '1857', '1359', '1859', '1459', '1354', '1454', '1854',
       '1954', '7303', '7307', '1340', '1840', '4701', '4702', '4800',
       '4351', '4352', '8020', '8117', '8217', '8218', '8116', '8216',
       '6446', '6447', '6534', '6635', '6429', '6529', '9036', '9305',
       '9301', '9929', '9225', '9224', '9494', '9117', '9115', '9113',
       '9114', '9790', '9116', '9672', '9930', '9051', '9309', '9088',
       '3916', '9307', '9424', '9486', '9204', '9556', '9563', '9562',
       '9461', '9435', '9489', '9488', '9691', '9180', '9306', '9623',
       '9501', '9414', '9692', '9104', '9784', '9797', '9266', '9106',
       '9487', '9433', '9490', '9022', '9121', '9122', '9119', '9260',
       '9304', '9419', '9492', '9202', '9896', '8911', '9181', '9786',
       '9105', '9750', '9708', '8111', '8119', '8018', '8118', '6962',
       '6331', '6431', '8114', '8014', '8015', '6443', '6543', '6428',
       '6528', '4251', '4252', '6634', '6335', '6435', '6436', '4500',
       '4503', '4513', '4180', '4181', '4182', '5108', '5112', '5101',
       '5111', '7076', '3712', '1021', '1022', '1023', '3604', '3609',
       '3612', '3614', '7841', '1771', '1991', '1873', '1973', '1994',
       '1975', '1776', '1777', '1977', '1268', '1168', '1470', '1974',
       '3509', '3513', '3512', '3517', '3518', '3519', '1998', '1883',
       '1983', '1993', '1781', '1791', '1978', '1882', '1982', '1985',
       '1889', '1471', '1984', '4150', '9810', '7949', '7086', '7947',
       '9162', '9120', '5107', '6749', '6849', '5121', '5222', '5223',
       '6968', '7040', '4401', '4440', '4441', '6991', '6992', '6873',
       '6874', '7241', '7049', '7069', '7079', '7044', '7048', '7047',
       '7067', '7043', '7063', '7041', '7045', '7042', '8021', '8214',
       '1890', '2950', '2951', '2952', '2953', '2954', '2956', '2957',
       '2958', '2959', '2960', '2961', '2963', '2964', '2966', '2967',
       '2968', '2969', '2970', '2971', '2972', '2973', '2975', '2976',
       '2977', '2979', '2980', '2981', '2982', '2984', '9060', '9800',
       '9354', '9699', '9380', '9053', '9799', '9392', '9252', '9961',
       '9407', '9519', '9390', '9671', '9355', '9324', '9345', '9656',
       '9946', '9176', '9491', '9513', '9764', '9695', '9399', '9334',
       '9751', '9927', '9212', '9602', '9111', '9811', '9835', '1061',
       '1961', '1953', '9201', '9455', '9484', '9432', '9193', '7305',
       '8115', '2965', '2983', '2987', '2988', '2989', '6978', '7064',
       '7068', '7061', '7065', '7062', '9792', '9322', '9643', '9687',
       '9876', '9953', '9023', '9875', '9344', '9868', '9880', '9393',
       '9819', '9383', '9851', '9340', '9866', '9640', '9663', '9890',
       '9889', '9376', '9475', '1066', '1966', '1967', '1968', '3501',
       '1053', '1057', '1957', '4359', '9801', '9422', '9416', '9436',
       '9460', '9420', '9421', '9864', '9107', '9705', '7300', '6434',
       '3702', '3508', '1749', '1989', '1986', '9838', '9310', '9315',
       '9453', '9511', '9363', '9877', '5105', '6649', '2955', '2962',
       '2978', '5120', '9831', '6965', '1892', '1941', '6379', '9690',
       '9000', '9693', '9149', '9954', '9217', '9711', '9497', '9955',
       '9670', '9445', '9919', '9694', '9757', '9145', '9684', '9362',
       '9426', '9773', '9709', '1769', '1056', '9312', '3703', '6536',
       '1898', '4501', '9359', '9758', '9308', '9216', '5102', '9828',
       '6877', '6980', '6963', '6369', '7059', '6976', '9950', '9680',
       '9685', '9636', '9756', '9219', '9785', '9481', '9873', '9952',
       '9183', '9366', '9483', '9350', '9634', '9882', '9870', '1962',
       '1964', '1855', '1955', '4350', '4600', '9387', '9423', '6876',
       '1981', '7054', '9158', '9450', '6349', '6449', '6549', '9869',
       '6979', '6863', '9341', '9382', '9921', '9659', '9512', '9661',
       '9654', '9629', '1969', '7302', '1948', '1956', '1054', '9459',
       '9365', '9853', '9867', '5106', '9824', '6969', '6977', '6966',
       '7077', '1999', '6985', '9630', '9502', '9752', '9945', '9932',
       '8011', '9451', '9156', '9198', '9652', '9653', '4100', '9931',
       '9454', '9172', '9428', '9651', '9398', '9397', '9754', '9903',
       '9127', '9637', '1064', '1065', '1965', '1949', '1051', '9103',
       '1773', '4797', '6997', '9157', '9482', '9503', '6350', '6964',
       '9197', '9391', '9425', '9427', '9448', '9948', '3603', '9473',
       '9330', '9469', '9396', '9622', '9438', '9924', '9182', '9949',
       '9822', '9477', '7301', '1848', '1850', '9108', '3503', '1980',
       '7096', '7098', '6334', '9856', '9437', '9222', '9942', '9843',
       '1055', '4700', '9704', '3704', '1774', '6986', '6328', '9220',
       '6865', '7084', '7094', '9842', '9845', '9937', '9938', '9923',
       '9449', '9189', '9439', '9178', '9939', '1068', '6975', '1959',
       '9415', '8016', '3502', '1992', '6878', '6333', '6674', '6982',
       '9371', '9374', '9612', '9934', '9935', '9331', '9329', '9936',
       '9170', '9507', '9618', '1952', '9412', '6535', '7090', '9175',
       '9126', '5020', '9326', '9320', '9323', '9818', '9468', '9606',
       '1950', '9405', '9403', '9413', '1971', '1979', '5001', '6869',
       '6879', '6981', '1256', '6185', '6385', '9605', '9920', '9348',
       '9352', '9174', '1052', '4300', '9404', '4502', '6342', '6983',
       '7093', '7091', '7095', '6332', '9318', '9343', '9346', '9347',
       '9356', '9504', '9613', '9933', '9999', '3608', '9342', '9357',
       '9358', '9171', '9327', '1063', '1017', '1019', '7304', '4250',
       '6329', '4400', '6376', '5030', '3601', '6343', '6988', '9206',
       '6880', '6336', '6340', '1050', '9402', '3507', '7089', '7099',
       '6359', '7081', '7085', '3602', '1020', '7088', '7087', '7097',
       '6996', '7267', '7083', '1370', '1472', '1473', '1474', '1778',
       '3515', '8127', '1475', '8121', '0', '1446', '1449', '1269',
       '3520', '7110', '1480', '1481', nan, '9580', '9570', '9564',
       '9571', '9574', '9582', '9520', '9515', '9264', '9273', '9261',
       '3927', '3904', '9299', '9086', '9165', '9298', '9259', '9295',
       '3932', '3923', '3922', '1501', '3913', '9276', '9992', '9168',
       '9977', '9169', '9516', '7914', '9284', '3910', '9073', '5900',
       '9099', '9281', '9560', '3925', '9084', '7905', '9081', '7916',
       '7909', '3930', '8947', '9092', '9565', '7901', '9094', '9091',
       '9231', '9068', '9067', '9065', '9263', '7908', '9049', '3921',
       '9979', '9087', '8903', '7902', '9085', '8909', '9576', '9098',
       '9095', '7913', '3936', '3929', '9097', '7907', '9093', '7903',
       '8928', '9572', '9569', '8902', '9557', '9279', '3912', '9270',
       '9561', '3917', '7904', '8920', '3934', '9647', '8921', '9976',
       '9981', '8918', '9635', '8934', '7911', '9277', '3924', '3914',
       '9167', '9134', '3926', '9296', '3933', '1500', '9718', '9257',
       '9089', '9135', '9293', '9288', '9137', '9133', '9728', 'TODOS'],
      dtype=object)

In [ ]:
list(tabla_cpp['COD_PLAN'].unique())

['3701',
 '3711',
 '7330',
 '4601',
 '4602',
 '4609',
 '5110',
 '5210',
 '5310',
 '4260',
 '5031',
 '5032',
 '4110',
 '4111',
 '3605',
 '3607',
 '3611',
 '3613',
 '5501',
 '9820',
 '9777',
 '9891',
 '9895',
 '9024',
 '9677',
 '9058',
 '9042',
 '9798',
 '9642',
 '9255',
 '9638',
 '9682',
 '9645',
 '9779',
 '9966',
 '9254',
 '9796',
 '9641',
 '9965',
 '9218',
 '9131',
 '9793',
 '9128',
 '9767',
 '9628',
 '9043',
 '9130',
 '3900',
 '9632',
 '9625',
 '9780',
 '9057',
 '9844',
 '9825',
 '9969',
 '9253',
 '9227',
 '9892',
 '9517',
 '9678',
 '9897',
 '9782',
 '9781',
 '9928',
 '9369',
 '9957',
 '9775',
 '9627',
 '9055',
 '9617',
 '9926',
 '7320',
 '7100',
 '9215',
 '9230',
 '9223',
 '9214',
 '9626',
 '9372',
 '9476',
 '9769',
 '9124',
 '9109',
 '9110',
 '9256',
 '9186',
 '9776',
 '9410',
 '9411',
 '9479',
 '9213',
 '9508',
 '9205',
 '9514',
 '8012',
 '8112',
 '9815',
 '9807',
 '9871',
 '9865',
 '9812',
 '9803',
 '9817',
 '9823',
 '9884',
 '9808',
 '9813',
 '9860',
 '9804',
 '9836',
 '9894',
 '9816',
 '9833',
 '9814',
 '9805',
 '9893',
 '9806',
 '1341',
 '1841',
 '1444',
 '1441',
 '1741',
 '1440',
 '1361',
 '1461',
 '1861',
 '1362',
 '1462',
 '1862',
 '1445',
 '1363',
 '1463',
 '1863',
 '1963',
 '1365',
 '1465',
 '1865',
 '1366',
 '1466',
 '1866',
 '1067',
 '1367',
 '1467',
 '1867',
 '1018',
 '1368',
 '1468',
 '1868',
 '1369',
 '1469',
 '1669',
 '1869',
 '1442',
 '1364',
 '1464',
 '1864',
 '1443',
 '3506',
 '3511',
 '3514',
 '7311',
 '7312',
 '1349',
 '1849',
 '1353',
 '1853',
 '1351',
 '1451',
 '1851',
 '1951',
 '1352',
 '1852',
 '1355',
 '1455',
 '1356',
 '1856',
 '1357',
 '1857',
 '1359',
 '1859',
 '1459',
 '1354',
 '1454',
 '1854',
 '1954',
 '7303',
 '7307',
 '1340',
 '1840',
 '4701',
 '4702',
 '4800',
 '4351',
 '4352',
 '8020',
 '8117',
 '8217',
 '8218',
 '8116',
 '8216',
 '6446',
 '6447',
 '6534',
 '6635',
 '6429',
 '6529',
 '9036',
 '9305',
 '9301',
 '9929',
 '9225',
 '9224',
 '9494',
 '9117',
 '9115',
 '9113',
 '9114',
 '9790',
 '9116',
 '9672',
 '9930',
 '9051',
 '9309',
 '9088',
 '3916',
 '9307',
 '9424',
 '9486',
 '9204',
 '9556',
 '9563',
 '9562',
 '9461',
 '9435',
 '9489',
 '9488',
 '9691',
 '9180',
 '9306',
 '9623',
 '9501',
 '9414',
 '9692',
 '9104',
 '9784',
 '9797',
 '9266',
 '9106',
 '9487',
 '9433',
 '9490',
 '9022',
 '9121',
 '9122',
 '9119',
 '9260',
 '9304',
 '9419',
 '9492',
 '9202',
 '9896',
 '8911',
 '9181',
 '9786',
 '9105',
 '9750',
 '9708',
 '8111',
 '8119',
 '8018',
 '8118',
 '6962',
 '6331',
 '6431',
 '8114',
 '8014',
 '8015',
 '6443',
 '6543',
 '6428',
 '6528',
 '4251',
 '4252',
 '6634',
 '6335',
 '6435',
 '6436',
 '4500',
 '4503',
 '4513',
 '4180',
 '4181',
 '4182',
 '5108',
 '5112',
 '5101',
 '5111',
 '7076',
 '3712',
 '1021',
 '1022',
 '1023',
 '3604',
 '3609',
 '3612',
 '3614',
 '7841',
 '1771',
 '1991',
 '1873',
 '1973',
 '1994',
 '1975',
 '1776',
 '1777',
 '1977',
 '1268',
 '1168',
 '1470',
 '1974',
 '3509',
 '3513',
 '3512',
 '3517',
 '3518',
 '3519',
 '1998',
 '1883',
 '1983',
 '1993',
 '1781',
 '1791',
 '1978',
 '1882',
 '1982',
 '1985',
 '1889',
 '1471',
 '1984',
 '4150',
 '9810',
 '7949',
 '7086',
 '7947',
 '9162',
 '9120',
 '5107',
 '6749',
 '6849',
 '5121',
 '5222',
 '5223',
 '6968',
 '7040',
 '4401',
 '4440',
 '4441',
 '6991',
 '6992',
 '6873',
 '6874',
 '7241',
 '7049',
 '7069',
 '7079',
 '7044',
 '7048',
 '7047',
 '7067',
 '7043',
 '7063',
 '7041',
 '7045',
 '7042',
 '8021',
 '8214',
 '1890',
 '2950',
 '2951',
 '2952',
 '2953',
 '2954',
 '2956',
 '2957',
 '2958',
 '2959',
 '2960',
 '2961',
 '2963',
 '2964',
 '2966',
 '2967',
 '2968',
 '2969',
 '2970',
 '2971',
 '2972',
 '2973',
 '2975',
 '2976',
 '2977',
 '2979',
 '2980',
 '2981',
 '2982',
 '2984',
 '9060',
 '9800',
 '9354',
 '9699',
 '9380',
 '9053',
 '9799',
 '9392',
 '9252',
 '9961',
 '9407',
 '9519',
 '9390',
 '9671',
 '9355',
 '9324',
 '9345',
 '9656',
 '9946',
 '9176',
 '9491',
 '9513',
 '9764',
 '9695',
 '9399',
 '9334',
 '9751',
 '9927',
 '9212',
 '9602',
 '9111',
 '9811',
 '9835',
 '1061',
 '1961',
 '1953',
 '9201',
 '9455',
 '9484',
 '9432',
 '9193',
 '7305',
 '8115',
 '2965',
 '2983',
 '2987',
 '2988',
 '2989',
 '6978',
 '7064',
 '7068',
 '7061',
 '7065',
 '7062',
 '9792',
 '9322',
 '9643',
 '9687',
 '9876',
 '9953',
 '9023',
 '9875',
 '9344',
 '9868',
 '9880',
 '9393',
 '9819',
 '9383',
 '9851',
 '9340',
 '9866',
 '9640',
 '9663',
 '9890',
 '9889',
 '9376',
 '9475',
 '1066',
 '1966',
 '1967',
 '1968',
 '3501',
 '1053',
 '1057',
 '1957',
 '4359',
 '9801',
 '9422',
 '9416',
 '9436',
 '9460',
 '9420',
 '9421',
 '9864',
 '9107',
 '9705',
 '7300',
 '6434',
 '3702',
 '3508',
 '1749',
 '1989',
 '1986',
 '9838',
 '9310',
 '9315',
 '9453',
 '9511',
 '9363',
 '9877',
 '5105',
 '6649',
 '2955',
 '2962',
 '2978',
 '5120',
 '9831',
 '6965',
 '1892',
 '1941',
 '6379',
 '9690',
 '9000',
 '9693',
 '9149',
 '9954',
 '9217',
 '9711',
 '9497',
 '9955',
 '9670',
 '9445',
 '9919',
 '9694',
 '9757',
 '9145',
 '9684',
 '9362',
 '9426',
 '9773',
 '9709',
 '1769',
 '1056',
 '9312',
 '3703',
 '6536',
 '1898',
 '4501',
 '9359',
 '9758',
 '9308',
 '9216',
 '5102',
 '9828',
 '6877',
 '6980',
 '6963',
 '6369',
 '7059',
 '6976',
 '9950',
 '9680',
 '9685',
 '9636',
 '9756',
 '9219',
 '9785',
 '9481',
 '9873',
 '9952',
 '9183',
 '9366',
 '9483',
 '9350',
 '9634',
 '9882',
 '9870',
 '1962',
 '1964',
 '1855',
 '1955',
 '4350',
 '4600',
 '9387',
 '9423',
 '6876',
 '1981',
 '7054',
 '9158',
 '9450',
 '6349',
 '6449',
 '6549',
 '9869',
 '6979',
 '6863',
 '9341',
 '9382',
 '9921',
 '9659',
 '9512',
 '9661',
 '9654',
 '9629',
 '1969',
 '7302',
 '1948',
 '1956',
 '1054',
 '9459',
 '9365',
 '9853',
 '9867',
 '5106',
 '9824',
 '6969',
 '6977',
 '6966',
 '7077',
 '1999',
 '6985',
 '9630',
 '9502',
 '9752',
 '9945',
 '9932',
 '8011',
 '9451',
 '9156',
 '9198',
 '9652',
 '9653',
 '4100',
 '9931',
 '9454',
 '9172',
 '9428',
 '9651',
 '9398',
 '9397',
 '9754',
 '9903',
 '9127',
 '9637',
 '1064',
 '1065',
 '1965',
 '1949',
 '1051',
 '9103',
 '1773',
 '4797',
 '6997',
 '9157',
 '9482',
 '9503',
 '6350',
 '6964',
 '9197',
 '9391',
 '9425',
 '9427',
 '9448',
 '9948',
 '3603',
 '9473',
 '9330',
 '9469',
 '9396',
 '9622',
 '9438',
 '9924',
 '9182',
 '9949',
 '9822',
 '9477',
 '7301',
 '1848',
 '1850',
 '9108',
 '3503',
 '1980',
 '7096',
 '7098',
 '6334',
 '9856',
 '9437',
 '9222',
 '9942',
 '9843',
 '1055',
 '4700',
 '9704',
 '3704',
 '1774',
 '6986',
 '6328',
 '9220',
 '6865',
 '7084',
 '7094',
 '9842',
 '9845',
 '9937',
 '9938',
 '9923',
 '9449',
 '9189',
 '9439',
 '9178',
 '9939',
 '1068',
 '6975',
 '1959',
 '9415',
 '8016',
 '3502',
 '1992',
 '6878',
 '6333',
 '6674',
 '6982',
 '9371',
 '9374',
 '9612',
 '9934',
 '9935',
 '9331',
 '9329',
 '9936',
 '9170',
 '9507',
 '9618',
 '1952',
 '9412',
 '6535',
 '7090',
 '9175',
 '9126',
 '5020',
 '9326',
 '9320',
 '9323',
 '9818',
 '9468',
 '9606',
 '1950',
 '9405',
 '9403',
 '9413',
 '1971',
 '1979',
 '5001',
 '6869',
 '6879',
 '6981',
 '1256',
 '6185',
 '6385',
 '9605',
 '9920',
 '9348',
 '9352',
 '9174',
 '1052',
 '4300',
 '9404',
 '4502',
 '6342',
 '6983',
 '7093',
 '7091',
 '7095',
 '6332',
 '9318',
 '9343',
 '9346',
 '9347',
 '9356',
 '9504',
 '9613',
 '9933',
 '9999',
 '3608',
 '9342',
 '9357',
 '9358',
 '9171',
 '9327',
 '1063',
 '1017',
 '1019',
 '7304',
 '4250',
 '6329',
 '4400',
 '6376',
 '5030',
 '3601',
 '6343',
 '6988',
 '9206',
 '6880',
 '6336',
 '6340',
 '1050',
 '9402',
 '3507',
 '7089',
 '7099',
 '6359',
 '7081',
 '7085',
 '3602',
 '1020',
 '7088',
 '7087',
 '7097',
 '6996',
 '7267',
 '7083',
 '1370',
 '1472',
 '1473',
 '1474',
 '1778',
 '3515',
 '8127',
 '1475',
 '8121',
 '0',
 '1446',
 '1449',
 '1269',
 '3520',
 '7110',
 '1480',
 '1481',
 nan,
 '9580',
 '9570',
 '9564',
 '9571',
 '9574',
 '9582',
 '9520',
 '9515',
 '9264',
 '9273',
 '9261',
 '3927',
 '3904',
 '9299',
 '9086',
 '9165',
 '9298',
 '9259',
 '9295',
 '3932',
 '3923',
 '3922',
 '1501',
 '3913',
 '9276',
 '9992',
 '9168',
 '9977',
 '9169',
 '9516',
 '7914',
 '9284',
 '3910',
 '9073',
 '5900',
 '9099',
 '9281',
 '9560',
 '3925',
 '9084',
 '7905',
 '9081',
 '7916',
 '7909',
 '3930',
 '8947',
 '9092',
 '9565',
 '7901',
 '9094',
 '9091',
 '9231',
 '9068',
 '9067',
 '9065',
 '9263',
 '7908',
 '9049',
 '3921',
 '9979',
 '9087',
 '8903',
 '7902',
 '9085',
 '8909',
 '9576',
 '9098',
 '9095',
 '7913',
 '3936',
 '3929',
 '9097',
 '7907',
 '9093',
 '7903',
 '8928',
 '9572',
 '9569',
 '8902',
 '9557',
 '9279',
 '3912',
 '9270',
 '9561',
 '3917',
 '7904',
 '8920',
 '3934',
 '9647',
 '8921',
 '9976',
 '9981',
 '8918',
 '9635',
 '8934',
 '7911',
 '9277',
 '3924',
 '3914',
 '9167',
 '9134',
 '3926',
 '9296',
 '3933',
 '1500',
 '9718',
 '9257',
 '9089',
 '9135',
 '9293',
 '9288',
 '9137',
 '9133',
 '9728',
 'TODOS']

In [ ]:
sel=st.selectbox("Selecciona el código a visualizar:", 
         list(tabla_cpp['COD_PLAN'].unique()))

2026-04-27 12:05:30.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:05:30.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:05:30.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:05:30.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:05:30.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:05:30.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:05:30.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
sel

'3701'

In [ ]:
tabla_filtrada_3=tabla_cpp[(tabla_cpp['COD_PLAN']==sel) & (tabla_cpp['SIES']==sel_2)]

NameError: name 'sel_2' is not defined

In [ ]:
sel_2=st.selectbox("Selecciona el código a visualizar:", 
         list(tabla_filtrada_2['SIES'].unique()))

2026-04-27 12:22:26.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:22:26.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:22:26.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:22:26.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:22:26.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:22:26.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-27 12:22:26.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
tabla_filtrada_3=tabla_cpp[(tabla_cpp['COD_PLAN']==sel) & (tabla_cpp['SIES']==sel_2)]

In [ ]:
tabla_filtrada_3

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701,2025.0,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2025-3701
377,2024-3701,3701,2024.0,2024-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012024.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2024-3701
746,2023-3701,3701,2023.0,2023-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012023.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2023-3701
1139,2022-3701,3701,2022.0,2022-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012022.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2022-3701
1515,2021-3701,3701,2021.0,2021-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012021.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2021-3701
1889,2020-3701,3701,2020.0,2020-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012020.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2020-3701
2288,2019-3701,3701,2019.0,2019-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012019.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2019-3701
2712,2018-3701,3701,2018.0,2018-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012018.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2018-3701
3108,2017-3701,3701,2017.0,2017-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012017.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2017-3701
3507,2016-3701,3701,2016.0,2016-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012016.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2016-3701
3900,2015-3701,3701,2015.0,2015-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012015.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2015-3701
4265,2014-3701,3701,2014.0,2014-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012014.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2014-3701
4627,2013-3701,3701,2013.0,2013-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012013.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2013-3701
4946,2012-3701,3701,2012.0,2012-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012012.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2012-3701
5268,2011-3701,3701,2011.0,2011-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012011.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2011-3701
5564,2010-3701,3701,2010.0,2010-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012010.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2010-3701
5852,2009-3701,3701,2009.0,2009-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012009.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2009-3701
6134,2008-3701,3701,2008.0,2008-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012008.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2008-3701
6424,2007-3701,3701,2007.0,2007-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012007.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2007-3701
6708,2006-3701,3701,2006.0,2006-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012006.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2006-3701
6949,2005-3701,3701,2005.0,2005-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012005.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2005-3701
7192,2004-3701,3701,2004.0,2004-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012004.0,I71S1C2J1V1,...,60.0,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60.0,True,Facultad de Administración y Economía,64.0,Departamento de Gestión y Políticas Públicas,True,2004-3701

No kernel connected

No kernel connected