Connected to base (Python 3.12.4)

In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import numpy as np
from gspread_dataframe import set_with_dataframe

In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import numpy as np
from gspread_dataframe import set_with_dataframe

# Configurar el alcance y credenciales
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('/home/xenomorfo/Descargas/bamboo-sweep-465617-i4-06b9bd6f36a5.json', scope)
client = gspread.authorize(credentials)
#jose-hoyos-usach-cl@bamboo-sweep-465617-i4.iam.gserviceaccount.com 
#https://docs.google.com/spreadsheets/d/17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E/edit?gid=1818427118#gid=1818427118
# Abrir la hoja de cálculo por ID
spreadsheet = client.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
credentials = ServiceAccountCredentials.\
from_json_keyfile_name('/home/xenomorfo/Descargas/bamboo-sweep-465617-i4-06b9bd6f36a5.json', scope)
# Abrir la hoja de cálculo por ID


CPP_DR = (
gspread.authorize(credentials)
.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
.get_worksheet(0)
.get_all_values()
# índice 0 es la primera hoja
)



CPP_DR = pd.DataFrame(CPP_DR[1:], columns=CPP_DR[0])

CPP_DR['ANHO_PLAN'] = CPP_DR['ANHO'] +'-'+ CPP_DR['COD_PLAN2']
CPP_DR['ANHO_SIES'] = CPP_DR['ANHO'] +'-'+ CPP_DR['SIES']


CPP_DR

CPP_CARO = (
gspread.authorize(credentials)
.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
.worksheet("CPP_CARO_2")
.get_all_values()
# índice 0 es la primera hoja
)
CPP_CARO = pd.DataFrame(CPP_CARO[2:], columns=CPP_CARO[0])

CPP_DR['ANHO_PLAN'].astype(str)
CPP_CARO['ANHO_PLAN'].astype(str)



#CPP_DR['ANHO_PLAN'].isin(CPP_CARO['ANHO_PLAN']).astype(int)

#CPP_CARO['ANHO_PLAN'].isin(CPP_DR['ANHO_PLAN']).astype(int)
CPP_DR.drop_duplicates()

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701,2025,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025,I71S1C2J1V1,...,60,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60,TRUE,Facultad de Administración y Economía,64,Departamento de Gestión y Políticas Públicas,TRUE,2025-3701
1,2025-3711,3711,2025,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025,I71S1C2J1V1,...,60,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60,TRUE,Facultad de Administración y Economía,64,Departamento de Gestión y Políticas Públicas,TRUE,2025-3711
2,2025-7330,7330,2025,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025,I71S1C913J1V1,...,65,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65,TRUE,Facultad Tecnológica,67,Departamento de Tecnologias de Gestión,TRUE,2025-7330
3,2025-4601,4601,2025,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025,I71S1C39J1V1,...,50,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50,TRUE,Facultad de Ciencia,51,Departamento de Matemática y Ciencia de la Com...,TRUE,2025-4601
4,2025-4602,4602,2025,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025,I71S1C39J1V1,...,50,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50,TRUE,Facultad de Ciencia,51,Departamento de Matemática y Ciencia de la Com...,TRUE,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,2024-9107,9107,2024,2024-I71S1C66J2V1,MAGÍSTER EN TELECOMUNICACIONES,,,,,I71S1C66J2V1,...,,,,40,FALSE,Facultad de Ingeniería,41,Departamento de Ingeniería Eléctrica,,2024-9107
7786,2024-9137,9137,2024,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,,,,,I71S1C56J1V2,...,,,,40,FALSE,Facultad de Ingeniería,47,Departamento de Ingeniería Química y Bioprocesos,,2024-9137
7787,2021-9484,9484,2021,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,,,,,I71S1C221J2V1,...,,,,55,FALSE,Facultad de Humanidades,59,Departamento de Educación,,2021-9484
7788,2022-9193,9193,2022,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",,,,,I71S1C398J2V1,...,,,,40,FALSE,Facultad de Ingeniería,40,Facultad de Ingeniería,,2022-9193
7789,2025-9728,9728,2025,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,,,,,I71S1C280J3V1,...,,,,94,FALSE,Facultad de Arquitectura y Ambiente Construido,94,Facultad de Arquitectura y Ambiente Construido,,2025-9728

In [ ]:
CPP_DR.to_csv("CPP_DR.csv", index=False)

In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import numpy as np
from gspread_dataframe import set_with_dataframe

# Configurar el alcance y credenciales
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('/home/xenomorfo/Descargas/bamboo-sweep-465617-i4-06b9bd6f36a5.json', scope)
client = gspread.authorize(credentials)
#jose-hoyos-usach-cl@bamboo-sweep-465617-i4.iam.gserviceaccount.com 
#https://docs.google.com/spreadsheets/d/17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E/edit?gid=1818427118#gid=1818427118
# Abrir la hoja de cálculo por ID
spreadsheet = client.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
# Abrir la hoja de cálculo por ID


CPP_DR = (
gspread.authorize(credentials)
.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
.get_worksheet(0)
.get_all_values()
# índice 0 es la primera hoja
)

CPP_DR = pd.DataFrame(CPP_DR[1:], columns=CPP_DR[0])

CPP_DR['ANHO_PLAN'] = CPP_DR['ANHO'] +'-'+ CPP_DR['COD_PLAN2']
CPP_DR['ANHO_SIES'] = CPP_DR['ANHO'] +'-'+ CPP_DR['SIES']


CPP_CARO = (
gspread.authorize(credentials)
.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
.worksheet("CPP_CARO_2")
.get_all_values()
# índice 0 es la primera hoja
)
CPP_CARO = pd.DataFrame(CPP_CARO[2:], columns=CPP_CARO[0])

CPP_DR['ANHO_PLAN'].astype(str)
CPP_CARO['ANHO_PLAN'].astype(str)

CPP_DR.drop_duplicates()

,ID,COD_PLAN,ANHO,ANHO_SIES,PLAN_NOMBRE,JORNADA_USACH,JORNADA_SIES,ESTADO_JORNADA,LLAVE,SIES,...,COD_FAC_,depto,FACULTAD_,COD_FAC,comparacion_facultad,FACULTAD,COD_DEPTO_2_CR,nombre_depto_cr,comparacion_cod_depto,ANHO_PLAN
0,2025-3701,3701,2025,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA,1,1,OK,37012025,I71S1C2J1V1,...,60,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60,TRUE,Facultad de Administración y Economía,64,Departamento de Gestión y Políticas Públicas,TRUE,2025-3701
1,2025-3711,3711,2025,2025-I71S1C2J1V1,ADMINISTRACIÓN PÚBLICA (D),1,1,OK,37112025,I71S1C2J1V1,...,60,DPTO DE GEST Y POLÍTIC PÚBLIC,FACULTAD DE ADMS Y ECONOMÍA,60,TRUE,Facultad de Administración y Economía,64,Departamento de Gestión y Políticas Públicas,TRUE,2025-3711
2,2025-7330,7330,2025,2025-I71S1C913J1V1,ANÁLISIS Y GESTIÓN DE PROCESOS PRODUCTIVOS,0,1,NO,73302025,I71S1C913J1V1,...,65,DPTO DE TECNOLOGÍAS GRALES,FACULTAD TECNOLÓGICA,65,TRUE,Facultad Tecnológica,67,Departamento de Tecnologias de Gestión,TRUE,2025-7330
3,2025-4601,4601,2025,2025-I71S1C39J1V1,LICENCIATURA EN CIENCIA DE LA COMPUTACIÓN,1,1,OK,46012025,I71S1C39J1V1,...,50,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50,TRUE,Facultad de Ciencia,51,Departamento de Matemática y Ciencia de la Com...,TRUE,2025-4601
4,2025-4602,4602,2025,2025-I71S1C39J1V1,ANALISTA EN COMPUTACIÓN CIENTÍFICA/LICENCIATUR...,1,1,OK,46022025,I71S1C39J1V1,...,50,DPTO MATEMÁT Y CS DE LA COMP,FACULTAD DE CIENCIA,50,TRUE,Facultad de Ciencia,51,Departamento de Matemática y Ciencia de la Com...,TRUE,2025-4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7786,2024-9137,9137,2024,2024-I71S1C56J1V2,MAGÍSTER EN CIENCIAS DE LA INGENIERÍA,,,,,I71S1C56J1V2,...,,,,40,FALSE,Facultad de Ingeniería,47,Departamento de Ingeniería Química y Bioprocesos,,2024-9137
7787,2021-9484,9484,2021,2021-I71S1C221J2V1,MAGÍSTER EN EDUCACIÓN,,,,,I71S1C221J2V1,...,,,,55,FALSE,Facultad de Humanidades,59,Departamento de Educación,,2021-9484
7788,2022-9193,9193,2022,2022-I71S1C398J2V1,"MAGÍSTER EN SEGURIDAD, PERITAJE Y AUDITORÍA EN...",,,,,I71S1C398J2V1,...,,,,40,FALSE,Facultad de Ingeniería,40,Facultad de Ingeniería,,2022-9193
7789,2025-9728,9728,2025,2025-I71S1C280J3V1,MÁSTER INTEGRADO EN DISEÑO ARQUITECTÓNICO,,,,,I71S1C280J3V1,...,,,,94,FALSE,Facultad de Arquitectura y Ambiente Construido,94,Facultad de Arquitectura y Ambiente Construido,,2025-9728
7790,,TODOS,,-,,,,,,,...,,,,,,,,,,-

In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import numpy as np
from gspread_dataframe import set_with_dataframe

# Configurar el alcance y credenciales
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('/home/xenomorfo/Descargas/bamboo-sweep-465617-i4-06b9bd6f36a5.json', scope)
client = gspread.authorize(credentials)
#jose-hoyos-usach-cl@bamboo-sweep-465617-i4.iam.gserviceaccount.com 
#https://docs.google.com/spreadsheets/d/17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E/edit?gid=1818427118#gid=1818427118
# Abrir la hoja de cálculo por ID
spreadsheet = client.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
# Abrir la hoja de cálculo por ID


CPP_DR = (
gspread.authorize(credentials)
.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
.get_worksheet(0)
.get_all_values()
# índice 0 es la primera hoja
)

CPP_DR = pd.DataFrame(CPP_DR[1:], columns=CPP_DR[0])

CPP_DR['ANHO_PLAN'] = CPP_DR['ANHO'] +'-'+ CPP_DR['COD_PLAN2']
CPP_DR['ANHO_SIES'] = CPP_DR['ANHO'] +'-'+ CPP_DR['SIES']


CPP_CARO = (
gspread.authorize(credentials)
.open_by_key('17LhWP9zmDMxmyqkmlB-PTc8kf7_p6LcFHdCGAhEvi9E')
.worksheet("CPP_CARO_2")
.get_all_values()
# índice 0 es la primera hoja
)
CPP_CARO = pd.DataFrame(CPP_CARO[2:], columns=CPP_CARO[0])

CPP_DR['ANHO_PLAN'].astype(str)
CPP_CARO['ANHO_PLAN'].astype(str)

CPP_DR.drop_duplicates()

CPP_DR.to_csv("CPP_DR.csv", index=False)

No kernel connected

No kernel connected